---
- hosts: dockerserver
  become: true
  gather_facts: false
  tasks:
    - name: Create hello_world container
      docker_container:
        name: hello-world
        image: hello_world
        state: started
        detach: yes
        volumes:
            - /root/container-data:/data
